routes:
  - type: rewrite
    source: /resume
    destination: /resume.html
  - type: rewrite
    source: /blog
    destination: /blog.html
  - type: rewrite
    source: /projects
    destination: /projects.html
  - type: rewrite
    source: /post
    destination: /post.html